- name: Create a sandbox instance
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    instance_type: t2.micro
    security_group: WEB-SSH-DMZ
    image: "ami-24959b47"
    region: ap-southeast-2
    key_name: kryptonite
    group_id: sg-e6be4382
    vpc_subnet_id: subnet-7878293e

  tasks:
    - name: Launch instance
      ec2:
         key_name: "{{ key_name }}"
         group_id: "{{ group_id }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         vpc_subnet_id: "{{ vpc_subnet_id }}"
         instance_tags:
           Name: buildstack-node01{{ lookup('pipe', 'date +%Y%m%d_%H%M%S') }}
         assign_public_ip: yes
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
      with_items: "{{ ec2.instances }}"

- name: Configure instance(s)
  hosts: launched
  become: True
  gather_facts: True
  tasks:
    - name: touch /etc/paulfile
      file:
        path: /etc/paulfile
        state: touch
        mode: "u=rw,g=r,o=r"

    - name: Enable selinux enforcing
      selinux: policy=targeted state=enforcing

    - name: Update packages
      yum: name='*' state=latest

    - name: Install EPEL
      yum: name=epel-release state=latest

    - action: yum pkg={{item}} state=latest
      with_items:
       - git
       - haproxy
       - noip
      ignore_errors: yes    
#     when: ansible_distribution == 'CentOS'
