---
- hosts: localhost
  connection: local
  user: buildstack
  gather_facts: False
  tasks:
  - name: create an EC2 instance
    local_action:
      module: ec2
      key_name: Paul-Default
      instance_type: t2.micro
      image: ami-2f10df44
      region: us-east-1
      group_id: sg-fd956f9a
      instance_tags:
        Name: buildstack-node01{{ lookup('pipe', 'date +%Y%m%d_%H%M%S') }}
      vpc_subnet_id: subnet-20da4057
      count: 1
      wait: yes
      assign_public_ip: yes
