---
- hosts: localhost
  connection: local
  user: buildstack
  gather_facts: False
  vars:
    AWS_ACCESS_KEY_ID: 'AKIAJZO6NIJRXORK4O4Q'
    AWS_SECRET_ACCESS_KEY: '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'
  tasks:
  - name: create an EC2 instance
    local_action:
      module: ec2
      key_name: Paul-Default
      instance_type: t2.micro
      image: ami-2f10df44
      region: us-east-1
      group_id: sg-fd956f9a
      instance_tags:
        Name: buildstack-node01{{ lookup('pipe', 'date +%Y%m%d_%H%M%S') }}
      vpc_subnet_id: subnet-20da4057
      count: 1
      wait: yes
      assign_public_ip: yes
